export const BOOKS_LIST_REQUEST = "BOOKS_LIST_REQUEST";
export const BOOKS_LIST_SUCCESS = "BOOKS_LIST_SUCCESS";
export const BOOKS_LIST_FAIL = "BOOKS_LIST_FAIL";

export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";
